python 3.11, getting sqllite error while deploying
RuntimeError: Your system has an unsupported version of sqlite3. Chroma

requires sqlite3 >= 3.35.0.

Please visit

https://docs.trychroma.com/troubleshooting#sqlite to learn how

to upgrade.